
web:
  html: ./dist
  upload: ./fileUpload

spring:
  application:
    name: Blueberry
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.html},file:${web.upload}
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
            misfireThreshold: 1000
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis:
  mapper-locations: classpath*:fun/bookish/blueberry/**/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
