# http
server:
  port: 10001

# 数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blueberry?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456

# sip
sip:
  name: GB28181-server
  host: 192.168.3.81
  port: 5060
  id: 13020000002000912345
  domain: 1302000000
  password: admin123
  traceLevel: NONE
  logMessageContent: false
  deviceExpires: 300

# 媒体服务器
media:
  ip: 192.168.3.81
  httpPort: 80
  rtpPort: 10086
  secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
  snapshotSavaPath: ./image/snapshots

# 视频质量检测
video-quality-detect:
  supportedArithmetics:
    - NOISE:噪声检测
    - STRIPE:条纹检测
    - COLOR_CAST:偏色检测
    - BRIGHTNESS:亮度检测
    - SHARPNESS:清晰度检测
    - ANGLE_CHANGE:角度变化检测

# 视频无人观看检测
video-no-reader-check:
  # 无人观看状态下视频存活时间
  aliveSeconds: 180

# 授权码
permission:
  code: E6pAkretV+PcRSXdwoLqA28j8/YjT2gUkOqwBR7YBV53KLuKQxyNZQs9tWSoK+7k5reST+shdwA=

# 日志配置
logging:
  config: classpath:logback-pro.xml